# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_text', models.TextField()),
                ('blog_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_published_date', models.DateTimeField(blank=True, null=True)),
                ('subscribe', models.TextField(default=0, max_length=50)),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
