# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='subscribe',
            new_name='blog_subscribe',
        ),
    ]
