# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170717_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subscribe',
            field=models.IntegerField(default=0),
        ),
    ]
