# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170717_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subscribe',
            field=models.CharField(max_length=50),
        ),
    ]
