# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170717_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subscribe',
        ),
    ]
