# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blog_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subscribe',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
