# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_author_name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
