# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_blog_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_author_name',
        ),
    ]
